apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-box
spec:
  replicas: 3 # Adjust the number of replicas as per your need
  selector:
    matchLabels:
      app: news-box
  template:
    metadata:
      labels:
        app: news-box
    spec:
      containers:
      - name: news-box
        image: suratkarmadhavi/news-box # Replace with your Docker image name
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: news-box-service
spec:
  selector:
    app: news-box # Matches the label defined in the deployment
  ports:
  - protocol: TCP
    port: 80 # Port exposed by the service
    targetPort: 5000 # Port the app is running on in the container
  type: NodePort # Can be NodePort or ClusterIP depending on your need
